### PR TITLE
feat(product_enablement): Add support for NGWAF.

### PR DESCRIPTION
**Pull request by kpfleming**

### CODE REVIEW

**Review by philippschulte — COMMENTED** [review]
This looks good to me but according to https://www.fastly.com/documentation/reference/api/products/enablement/ there are two more endpoints. Would it not make sense to add those to the test suite?

**Comment by kpfleming** [comment]
Yes it would, but that will need to be done as a separate task I believe. I'll enter an issue for that.

**Comment by kpfleming** [comment]
I've created (internal) issue CDTOOL-932 for adding the product configuration endpoints.

**Review by philippschulte — APPROVED** [review]
Thank you!

**Pull request merged**
