### PR TITLE
fastly: allow uploading compute package from memory

### PR DESCRIPTION
**Pull request by glerchundi**
This change adds support for uploading compute packages using memory instead of loading them from file paths. In order to preserve backward compatibility, it prioritises the presence of the package path over the in-memory content. It will only proceed to load from memory when the package path isn't present.

Signed-off-by: Gorka Lerchundi Osa <glertxundi@gmail.com>

### CODE REVIEW

**Review by Integralist — CHANGES_REQUESTED** [review]
Hi @glerchundi thanks for opening this PR.

This PR looks fine to me, just a couple of doc string fixes (added as suggested edits for you to just commit), but if you could also follow the steps in the [README.md](https://github.com/fastly/go-fastly#testing) for updating the relevant fixture files that would be great.

Thanks!

**Comment by glerchundi** [comment]
TFYR @Integralist, it was faster than next week so it's really appreciated! :D

I'm having a hard time trying to run the tests as they are panicking:

`make test FASTLY_TEST_SERVICE_ID="{SERVICE_ID}" FASTLY_API_KEY="{API_TOKEN_WITH_ACCESS_TO_SERVICE_ID}" TESTARGS="-run=..."`:
```
oroutine 462 [semacquire]:
sync.runtime_SemacquireMutex(0x8?, 0x80?, 0x1?)
        /opt/homebrew/Cellar/go/1.18.3/libexec/src/runtime/sema.go:71 +0x28
sync.(*Mutex).lockSlow(0x102a8f648)
        /opt/homebrew/Cellar/go/1.18.3/libexec/src/sync/mutex.go:162 +0x180
sync.(*Mutex).Lock(...)
        /opt/homebrew/Cellar/go/1.18.3/libexec/src/sync/mutex.go:81
github.com/fastly/go-fastly/v7/fastly.createTestVersion.func1(0x140001da9c0?)
        /Users/g.lerchundi-local/Code/src/github.com/glerchundi/go-fastly/fastly/fastly_test.go:177 +0xc4
github.com/fastly/go-fastly/v7/fastly.record(0x140001da9c0, {0x14000207b70, 0x1d}, 0x140002079d8)
        /Users/g.lerchundi-local/Code/src/github.com/glerchundi/go-fastly/fastly/fastly_test.go:61 +0xf8
github.com/fastly/go-fastly/v7/fastly.createTestVersion(0x140001da9c0?, {0x14000207b70?, 0x14000625560?}, {0x1400001a3c0?, 0x1027a73c0?})
        /Users/g.lerchundi-local/Code/src/github.com/glerchundi/go-fastly/fastly/fastly_test.go:176 +0x68
github.com/fastly/go-fastly/v7/fastly.TestClient_WAF_Versions(0x140001da9c0)
        /Users/g.lerchundi-local/Code/src/github.com/glerchundi/go-fastly/fastly/waf_version_test.go:18 +0x14c
testing.tRunner(0x140001da9c0, 0x102811708)
        /opt/homebrew/Cellar/go/1.18.3/libexec/src/testing/testing.go:1439 +0x110
created by testing.(*T).Run
        /opt/homebrew/Cellar/go/1.18.3/libexec/src/testing/testing.go:1486 +0x300
FAIL    github.com/fastly/go-fastly/v7/fastly   30.283s
FAIL
make: *** [test] Error 1
```

Any chance to run those by yourself or shed some light on what's going on?

**Comment by Integralist** [comment]
Hi @glerchundi 

> it was faster than next week so it's really appreciated!

No worries, I have some time in between a few projects to take a look at your PR 🙂 

Re: the fixtures panic'ing, let me try myself this week (likely today but I'm a bit behind on some things so I don't want to overpromise) and I'll let you know.

**Comment by Integralist** [comment]
> likely today but I'm a bit behind on some things so I don't want to overpromise

Actually, I managed to find time just now 🙂 

I'm not seeing a panic from your code when I run...

```
rm -r fastly/fixtures/package/*
make test FASTLY_TEST_SERVICE_ID="<MY_SERVICE_ID>" TESTARGS="-run=TestClient_Package"
```

> **NOTE**: I already have `FASTLY_API_KEY` set in my shell environment.

I do get an error though...

```
==> Testing go-fastly-customer
--- FAIL: TestClient_Package (4.11s)
    package_test.go:146: 400 - Bad Request:
                                                                                                                                                                                                                                              
            Title:  Bad request
            Detail: Failed to extract metadata from package
FAIL
FAIL    github.com/fastly/go-fastly/v7/fastly   5.409s
FAIL
make: *** [test] Error 1
```

Looking back at your stack trace it seems you were trying to run all the tests, although that should be fine but not when setting `FASTLY_TEST_SERVICE_ID` as then the test suite will try and look up your Service ID in the fixtures and there won't be any recorded fixtures with that ID. 

For example...

```
--- FAIL: TestClient_Servers (0.00s)
    fastly_test.go:167: Post "https://api.fastly.com/service/<MY_SERVICE_ID>/version": Requested interaction not found
```

> **NOTE**: After a fixture is updated we use `make fix-fixtures FASTLY_TEST_SERVICE_ID=<...>` to replace our own Service ID with a generic one for future test runs. 

So if I try and run the full test suite using FASTLY_TEST_SERVICE_ID then I DO see panics. Although I shouldn't see panics because go-vcr should just report that the fixture couldn't be found and fail the test. So that's interesting a panic occurs.

**Comment by glerchundi** [comment]
@Integralist thanks for taking the time to respond and with such level of detail. I've managed to run the test by just running the one that have tentatively changed and track down where was the code failing. AFAIK and  from my understanding, this failure is unrelated to this PR. PTAL to #385: https://github.com/fastly/go-fastly/pull/385/files#diff-048656e3a826c14652b659932e488aae3cb84ff67f20415258ec9f27984c9468.

**Comment by Integralist** [comment]
Thanks @glerchundi for finding/fixing that issue 👍🏻 

I've just requested one small change on the PR https://github.com/fastly/go-fastly/pull/385#pullrequestreview-1180468719

I'll get this PR merged now, and then if you wouldn't mind fixing up the other PR so I can merge it and I'll open a separate PR to update the fixtures for the changes in this PR.

**Review by Integralist — APPROVED** [review]

**Pull request merged**
