### PR TITLE
backends: allow clearing at least some fields on update

### PR DESCRIPTION
**Pull request by dkegel-fastly**
Partial fix for https://github.com/fastly/go-fastly/issues/371 ?

### CODE REVIEW

**Comment by dgryski** [comment]
I'm concerned about this causing subtle breakage for our users.

**Comment by dkegel-fastly** [comment]
Me, too.

**Comment by Integralist** [comment]
> I'm concerned about this causing subtle breakage for our users.

We can just do a major version update then, no? 

[This typo](https://github.com/fastly/go-fastly/blob/41260b8314dd09b4a9265260a461f94c5c5850b5/fastly/service_authorization.go#L30) has been bugging me for a bit so I could fix that and maybe some other breaking changes as part of the next major release.

**Comment by dgryski** [comment]
If we have a bunch of breaking changes lined up, that's not a bad plan.  We could write some tooling (semgrep/ruleguard) to detect/fix the common ones.

**Comment by dkegel-fastly** [comment]
One breaking change might be "generate this sdk with https://github.com/fastly/api-clients-generator/ "

**Comment by Integralist** [comment]
Closing in favour of https://github.com/fastly/go-fastly/pull/375

**Pull request closed without merging**
