### PR TITLE
Do not omit zero int values on create operations

### PR DESCRIPTION
**Pull request by smaeda-ks**
(mainly for TF provider)

https://github.com/fastly/terraform-provider-fastly/issues/129
https://github.com/fastly/terraform-provider-fastly/issues/109
https://github.com/fastly/terraform-provider-fastly/issues/87

### CODE REVIEW

**Comment by smaeda-ks** [comment]
@Integralist Do you think this requires updating test fixtures?

**Comment by smaeda-ks** [comment]
Also, we seem to have some inconsistencies between `int` vs `uint`.

**Comment by Integralist** [comment]
I'd personally prefer to regenerate the fixtures.

I agree there is an inconsistency. I typically use `int` by default, but I can appreciate that if we know we'll only ever need positive number then using `uint` makes sense. I wouldn't worry too much about this for now, especially if we consider in the future moving go-fastly to being code-generated.

**Review by Integralist — APPROVED** [review]
Approving ahead of fixtures being regenerated.

**Comment by smaeda-ks** [comment]
@Integralist updated fixtures.

**Review by Integralist — APPROVED** [review]

**Comment by smaeda-ks** [comment]
ok to merge? I don't have write access though

**Comment by Integralist** [comment]
Oh, sorry @smaeda-ks I'll merge now 😬

**Pull request merged**
